# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_oblast', models.CharField(blank=True, max_length=256)),
                ('address_raion', models.CharField(blank=True, max_length=256)),
                ('address_city', models.CharField(blank=True, max_length=256)),
                ('address_street', models.CharField(blank=True, max_length=256)),
                ('address_house', models.CharField(blank=True, max_length=10)),
                ('address_building', models.CharField(blank=True, max_length=10)),
                ('address_letter', models.CharField(blank=True, max_length=10)),
                ('purpose', models.CharField(blank=True, max_length=256)),
                ('number', models.CharField(blank=True, max_length=256)),
                ('maker', models.CharField(blank=True, max_length=256)),
                ('load', models.CharField(blank=True, max_length=256)),
                ('stops', models.IntegerField(blank=True)),
                ('speed', models.CharField(blank=True, max_length=256)),
                ('date', models.DateField(blank=True)),
                ('replacements', models.TextField(blank=True)),
                ('deadline', models.CharField(blank=True, max_length=256)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='applications.Application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('application_template', models.TextField(blank=True, verbose_name='Шаблон печати заявки')),
                ('contract_template', models.TextField(blank=True, verbose_name='Шаблон печати договора')),
                ('account_template', models.TextField(blank=True, verbose_name='Шаблон печати счета')),
                ('order_template', models.TextField(blank=True, verbose_name='Шаблон печати приказа')),
            ],
            options={
                'verbose_name': 'тип заявки',
                'verbose_name_plural': 'типы заявок',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.ApplicationType'),
        ),
    ]
