# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationentry',
            name='address_building',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='applicationentry',
            name='address_city',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='applicationentry',
            name='address_house',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='applicationentry',
            name='address_letter',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='applicationentry',
            name='address_oblast',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='applicationentry',
            name='address_raion',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='applicationentry',
            name='address_street',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='applicationentry',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicationentry',
            name='deadline',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='applicationentry',
            name='load',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='applicationentry',
            name='maker',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='applicationentry',
            name='number',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='applicationentry',
            name='purpose',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='applicationentry',
            name='replacements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicationentry',
            name='speed',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='applicationentry',
            name='stops',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='hints',
            field=models.TextField(blank=True),
        ),
    ]
