# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20170307_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(),
        ),
    ]
