# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20170309_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtype',
            name='account_template',
            field=models.TextField(blank=True),
        ),
    ]
