# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='advance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='terms',
            field=models.IntegerField(default=0),
        ),
    ]
