# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_auto_20170311_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('patr_name', models.CharField(max_length=128)),
            ],
        ),
    ]
