# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='head_specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heading_orders', to='shared.Specialist'),
        ),
        migrations.AddField(
            model_name='order',
            name='specialists',
            field=models.ManyToManyField(blank=True, to='shared.Specialist'),
        ),
    ]
